name: Publish role to Anisble Galaxy

on:
  push:
    branches:
      - 'master'

jobs:
  tag_publish_ansible_role:
    runs-on: ubuntu-latest
    name: Publish role to Ansible Galaxy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push repo tag
        id: tagging
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ORG_REPO_TAG }}
          DEFAULT_BUMP: patch
          WITH_V: "true"
          INITIAL_VERSION: 1.0.0

      - name: Publish role
        uses: robertdebock/galaxy-action@1.0.3
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}